### ISSUE TITLE
The command '/bin/ash -o pipefail -c composer install --no-interaction --no-dev' returned a non-zero code: 2

### ISSUE THREAD

**Issue by dfares1987** [mastria/hassio-addons#1]
boa tarde ao tentar atualizar para a ver 1.0.7 recebo esse erro e ao tentar desinstalar e instalar novamente mante o mesmo erro The command '/bin/ash -o pipefail -c composer install --no-interaction --no-dev' returned a non-zero code: 2

**Comment by mastria** [comment]
@dfares1987 sua instância tem acesso a internet? Aparenta ser erro de dependência.

**Comment by dfares1987** [comment]
boa noite sim tem acesso normal inclusive atualizei outros addons e o proprio hass io em seguida esse é o log do erro inteiro


Registrador: homeassistant.components.hassio
Fonte: components/hassio/websocket_api.py:135
integração: Home Assistant Supervisor (documentação, problemas)
Ocorreu pela primeira vez: 14:43:15 (1 ocorrências)
Último registro: 14:43:15

Failed to to call /addons/57ab9ac6_intelbras-solar/install - The command '/bin/ash -o pipefail -c composer install --no-interaction --no-dev' returned a non-zero code: 2

**Comment by mastria** [comment]
O problema foi resolvido.
